### ISSUE TITLE
VicareDiscoveryService fails if some properties are null

### ISSUE THREAD

**Issue by rtuck99** [rtuck99/openhab-binding#29]
2022-12-09 14:38:58.198 [WARN ] [care.internal.VicareDiscoveryService] - Unexpected error occurred scanning Viessmann API
java.lang.NullPointerException: null
at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
at java.util.ImmutableCollections$MapN.(ImmutableCollections.java:827) ~[?:?]
at java.util.Map.of(Map.java:1399) ~[?:?]
at com.qubular.openhab.binding.vicare.internal.VicareDiscoveryService.discoverHeating(VicareDiscoveryService.java:146) ~[?:?]
at com.qubular.openhab.binding.vicare.internal.VicareDiscoveryService.lambda$scanJob$0(VicareDiscoveryService.java:104) ~[?:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by rtuck99** [comment]
Fixed in 3.3.6
