### ISSUE TITLE
NPE on start of Glowmarkt handler

### ISSUE THREAD

**Issue by rtuck99** [rtuck99/openhab-binding#52]
java.lang.NullPointerException: Cannot invoke "org.openhab.core.thing.binding.ThingHandler.handleCommand(org.openhab.core.thing.ChannelUID, org.openhab.core.types.Command)" because "handler" is null
        at com.qubular.binding.glowmarkt.internal.GlowmarktBridgeHandler.lambda$resourceUpdateJob$1(GlowmarktBridgeHandler.java:153) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Seems to happen on binding start, but somehow doesn't seem to otherwise affect functioning.

**Comment by rtuck99** [comment]
Fixed in 4.0.1
