### ISSUE TITLE
Spurious NoSuchMethodError exceptions

### ISSUE THREAD

**Issue by rtuck99** [rtuck99/openhab-binding#53]
Nadalio reports

2023-08-05 15:28:23.061 [WARN ] [re.internal.VicareDeviceThingHandler] - Unexpected exception handling command REFRESH for channel vicare:heating:73a6950753:30d23790-ab86-3836-8e84-1c421bc1139d:heating_circuits_1_heating_curve_shift
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void org.openhab.core.library.types.DecimalType.<init>(double)'
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void org.openhab.core.library.types.DecimalType.<init>(double)'
	at com.qubular.openhab.binding.vicare.internal.VicareDeviceThingHandler$1.visit(VicareDeviceThingHandler.java:272) ~[?:?]
	at com.qubular.vicare.model.features.CurveFeature.accept(CurveFeature.java:32) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareDeviceThingHandler.lambda$syncHandleCommand$5(VicareDeviceThingHandler.java:171) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareDeviceThingHandler.syncHandleCommand(VicareDeviceThingHandler.java:170) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareDeviceThingHandler.lambda$handleCommand$3(VicareDeviceThingHandler.java:159) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	... 6 more

Also I see on my Glowmarkt binding occasionally
java.lang.NoSuchMethodError: 'void org.openhab.core.library.types.DecimalType.<init>(double)'
        at com.qubular.binding.glowmarkt.internal.GlowmarktVirtualEntityHandler.lambda$batchFetchHistoricData$12(GlowmarktVirtualEntityHandler.java:274) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.qubular.binding.glowmarkt.internal.GlowmarktVirtualEntityHandler.batchFetchHistoricData(GlowmarktVirtualEntityHandler.java:273) ~[?:?]
        at com.qubular.binding.glowmarkt.internal.GlowmarktVirtualEntityHandler.fetchHistoricDataForMissingPeriod(GlowmarktVirtualEntityHandler.java:254) ~[?:?]
        at com.qubular.binding.glowmarkt.internal.GlowmarktVirtualEntityHandler.fetchHistoricData(GlowmarktVirtualEntityHandler.java:227) ~[?:?]
        at com.qubular.binding.glowmarkt.internal.GlowmarktVirtualEntityHandler.handleCommand(GlowmarktVirtualEntityHandler.java:178) ~[?:?]
        at com.qubular.binding.glowmarkt.internal.GlowmarktBridgeHandler.lambda$resourceUpdateJob$1(GlowmarktBridgeHandler.java:153) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by rtuck99** [comment]
Can't reproduce this any more. Suspect it might have been down to a stale copy of the binding in the cache
