### ISSUE TITLE
Thread starvation and excessive log messages after possible HTTP connection stall

### ISSUE THREAD

**Issue by rtuck99** [rtuck99/openhab-binding#57]
I am having several exceptions in my log file several times during the day (probably due to my ISP changing the dynamic IP WAN address).

I have tried to understand the behaviour:
Probably when the binding fails to connect to the Viessmann cloud service, the binding sends the first two exceptions (I have two THINGS attached to the BRIDGE)

Unable to request features from IoT API

Then for every ITEM defined for the two THINGS I get the next group of exceptions:

Unexpected exception handling command REFRESH for channel CHANNEL_NAME java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker

Maybe instead of raising an exception, the binding should set to OFFLINE all the THINGS so that no queries will be sent to the cloud when there is no connection, avoiding pages of exceptions. What do you think?

See also thread on jetty mailing list at 
https://github.com/eclipse/jetty.project/issues/3891
which suggests that it is caused by the server disconnecting. I note that

HttpConnectionOverHTTP@a9ed3b::DecryptedEndPoint@785e84{l=/[192.168.88.5:38716](http://192.168.88.5:38716/),r=[api.viessmann.com/20.166.96.40:443,OPEN,fill=-,flush=-,to=1116127/0](http://api.viessmann.com/20.166.96.40:443,OPEN,fill=-,flush=-,to=1116127/0)}

indicates connection idle for 1116 seconds or more than 18 minutes. Possibly connection has been idle for a long time and then disconnected. Connection timeout should probably be reduced below polling threshold.

2023-08-18 09:00:58.431 [WARN ] [ar.vicare.internal.VicareServiceImpl] - Unable to request features from IoT API
java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@a9ed3b::DecryptedEndPoint@785e84{l=/[192.168.88.5:38716](http://192.168.88.5:38716/),r=[api.viessmann.com/20.166.96.40:443,OPEN,fill=-,flush=-,to=1116127/0](http://api.viessmann.com/20.166.96.40:443,OPEN,fill=-,flush=-,to=1116127/0)}
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101) ~[?:?]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:730) ~[?:?]
	at com.qubular.vicare.internal.VicareServiceImpl.getFeatures(VicareServiceImpl.java:233) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareBridgeHandler.lambda$getFeatures$8(VicareBridgeHandler.java:236) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1144) ~[?:?]
	at java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:3151) ~[?:?]
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1817) ~[?:?]
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareBridgeHandler.handleBridgedRefreshCommand(VicareBridgeHandler.java:181) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareDeviceThingHandler.syncHandleCommand(VicareDeviceThingHandler.java:169) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareDeviceThingHandler.lambda$handleCommand$3(VicareDeviceThingHandler.java:159) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.io.EOFException: HttpConnectionOverHTTP@a9ed3b::DecryptedEndPoint@785e84{l=/[192.168.88.5:38716](http://192.168.88.5:38716/),r=[api.viessmann.com/20.166.96.40:443,OPEN,fill=-,flush=-,to=1116127/0](http://api.viessmann.com/20.166.96.40:443,OPEN,fill=-,flush=-,to=1116127/0)}
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:385) ~[?:?]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1620) ~[?:?]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:269) ~[?:?]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:185) ~[?:?]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:80) ~[?:?]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131) ~[?:?]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172) ~[?:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[?:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164) ~[?:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[?:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[?:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-08-18 09:00:58.431 [WARN ] [ar.vicare.internal.VicareServiceImpl] - Unable to request features from IoT API
java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@a8ff3::DecryptedEndPoint@14ffbe3{l=/[192.168.88.5:38714](http://192.168.88.5:38714/),r=[api.viessmann.com/20.166.96.40:443,OPEN,fill=-,flush=-,to=1116181/0](http://api.viessmann.com/20.166.96.40:443,OPEN,fill=-,flush=-,to=1116181/0)}
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101) ~[?:?]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:730) ~[?:?]
	at com.qubular.vicare.internal.VicareServiceImpl.getFeatures(VicareServiceImpl.java:233) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareBridgeHandler.lambda$getFeatures$8(VicareBridgeHandler.java:236) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1144) ~[?:?]
	at java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:3151) ~[?:?]
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1817) ~[?:?]
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareBridgeHandler.handleBridgedRefreshCommand(VicareBridgeHandler.java:181) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareDeviceThingHandler.syncHandleCommand(VicareDeviceThingHandler.java:169) ~[?:?]
	at com.qubular.openhab.binding.vicare.internal.VicareDeviceThingHandler.lambda$handleCommand$3(VicareDeviceThingHandler.java:159) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
Caused by: java.io.EOFException: HttpConnectionOverHTTP@a8ff3::DecryptedEndPoint@14ffbe3{l=/[192.168.88.5:38714](http://192.168.88.5:38714/),r=[api.viessmann.com/20.166.96.40:443,OPEN,fill=-,flush=-,to=1116181/0](http://api.viessmann.com/20.166.96.40:443,OPEN,fill=-,flush=-,to=1116181/0)}
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.earlyEOF(HttpReceiverOverHTTP.java:385) ~[?:?]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1620) ~[?:?]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.shutdown(HttpReceiverOverHTTP.java:269) ~[?:?]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:185) ~[?:?]
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:80) ~[?:?]
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:131) ~[?:?]
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:172) ~[?:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[?:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164) ~[?:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[?:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) ~[?:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]

**Comment by rtuck99** [comment]
RejectedExecutionException occurs because join() is called from within another CompletableFuture, therefore will not block - see https://stackoverflow.com/questions/56413349/does-the-call-of-join-in-the-following-completablefuture-example-block-the-proce
