### ISSUE TITLE
If binding throws unhandled exception, things are no longer updated

### ISSUE THREAD

**Issue by rtuck99** [rtuck99/openhab-binding#7]
2022-10-05 08:13:07.818 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
        at com.qubular.vicare.internal.VicareServiceImpl.extractFeatures(VicareServiceImpl.java:189) ~[?:?]
        at com.qubular.vicare.internal.VicareServiceImpl.getFeatures(VicareServiceImpl.java:174) ~[?:?]
        at com.qubular.openhab.binding.vicare.internal.VicareBridgeHandler.getFeatures(VicareBridgeHandler.java:147) ~[?:?]
        at com.qubular.openhab.binding.vicare.internal.VicareBridgeHandler.handleBridgedDeviceCommand(VicareBridgeHandler.java:118) ~[?:?]
        at com.qubular.openhab.binding.vicare.internal.VicareDeviceThingHandler.handleCommand(VicareDeviceThingHandler.java:231) ~[?:?]
        at com.qubular.openhab.binding.vicare.internal.VicareBridgeHandler.lambda$featurePoller$0(VicareBridgeHandler.java:100) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by rtuck99** [comment]
Fixed in 3.3.3
